version: 2.1

executors:
    build-executor:
        machine:
            image: ubuntu-1604:201903-01

jobs:
    install-packages:
        executor: build-executor
        steps:
            - checkout
            - run:
                name: Install nuget
                command: sudo apt install nuget
            - run:
                name: Install dotnet-sdk-2.2
                command: | 
                            wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
                            sudo dpkg -i packages-microsoft-prod.deb
                            sudo apt install apt-transport-https
                            sudo apt update
                            sudo apt install dpkg
                            sudo apt install dotnet-sdk-2.2 -y
            - run:
                name: Install Signcode & download certificate
                command: | 
                            sudo apt install mono-devel --yes
                            wget $URL_TO_CERTIFICATE -O signing-certificate.pfx
                            cd /
                            pwd
            - persist_to_workspace:
                root: .
                paths:
                    - bin
    build:
        executor: build-executor
        environment:
            MAJOR_VERSION: 1
            MINOR_VERSION: 0
        steps:
            - attach_workspace:
                at: /home/circleci/project
            - run:
                name: Restore
                command: sudo dotnet restore
            - run:
                name: Build
                command: sudo dotnet build --configuration Release
            - run:
                name: Signing
                command: |  
                            openssl pkcs12 -in signing-certificate.pfx -out signing-certificate.crt -nokeys -clcerts -passin pass:$CERT_PASSWORD
                            openssl x509 -inform pem -in signing-certificate.crt -outform der -out signing-certificate.cer
                            cert2spc signing-certificate.cer signing-certificate.spc
                            sudo signcode -t http://timestamp.digicert.com -spc signing-certificate.spc bin/Release/netcoreapp2.2/*.dll
            - run:
                name: Pack
                command: sudo dotnet pack --no-build -p:PackageVersion=$MAJOR_VERSION.$MINOR_VERSION.$CIRCLE_BUILD_NUM --configuration Release
            - run:
                name: SignIn to AzureDevOps
                command: sudo nuget sources Add -Name "MyFeedName" -Source $NUGET_SOURCE -username $SOURCE_USERNAME -password $SOURCE_PASSWORD -StorePasswordInClearText
            - run:
                name: Push nuget
                command: |  
                            sudo cp ~/.config/NuGet/NuGet.Config ~/.nuget/NuGet/
                            sudo dotnet nuget push bin/Release/*.nupkg -s $NUGET_SOURCE -k $API_KEY
workflows:
    version: 2.1
    workflow:
        jobs:
        - install-packages:
            context: context
        - build:
            requires:
                - install-packages
            context: context
            filters:
                branches:
                    only: master